name: Build

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "bullet/docs/**"
      - "**.md"
      - "**.txt"
  pull_request:
    branches: [main, dev]
    paths-ignore:
      - "bullet/docs/**"
      - "**.md"
      - "**.txt"
  workflow_dispatch:
    branches: [main, dev]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: windows-latest
            cmake-args: -G 'MinGW Makefiles'
            make: mingw32-make

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "^3.5"

      - uses: mymindstorm/setup-emsdk@v8
        with:
          version: "latest"

      - run: emcc -v
      - run: python -V
      - run: cmake --version
      - run: ${{ matrix.make || 'make' }} --version
      - run: cmake -B build/cmake -DCLOSURE=1 -DCMAKE_TOOLCHAIN_FILE="${{env.EMSDK}}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" ${{ matrix.cmake-args }}
      - run: cmake --build build/cmake -- VERBOSE=1
      - run: npm ci

      - name: Test Ammo Javascript
        run: npx ava
        env:
          AMMO_BUILD: bin/ammo.js

      - name: Test Ammo WebAssembly
        run: npx ava
        env:
          AMMO_BUILD: bin/ammo.wasm.js

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: bin/**
